# Generated by Django 4.2 on 2026-03-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
